frontend:
  image: codemed:2.0
  ports:
    - 80:80
  environment:
    - VUE_APP_THEME=__cedro
    - VUE_APP_API_CORTEZ=http://192.168.1.68
    - VUE_APP_API_CEDRO=http://192.168.1.68
    - VUE_APP_MASK_ATTENDANCE_CORTEZ=3:9
    - VUE_APP_MASK_ATTENDANCE_CEDRO=3:5